### ISSUE TITLE
docs: replace old url

### ISSUE THREAD

**Issue by megatank58** [gominima/guide#3]
Replace the old URL at [landing page](https://github.com/gominima/guide/blob/main/docs/README.md?plain=1#L10) with `/preparations/`.

**Comment by Rounak-28** [comment]
@megatank58 I can work in this

**Comment by megatank58** [comment]
Feel free to make a PR

**Comment by Rounak-28** [comment]
@megatank58 Already opened a PR

**Comment by megatank58** [comment]
Thanks for your contribution, i went ahead and merged the PR
